import Head from 'next/head'
import dynamic from 'next/dynamic'
import { Modal } from '@/components/Modal'
import { useState } from 'react'
import { ChartPopulationInfo } from '@/components/ChartPopulationInfo'
import { Properties } from '@/components/map'
import Logo_Ubirata_Positive from '../../public/Logo_Ubirata_Positive.png'
import styles from '../styles/home.style.module.css'
import Image from 'next/image'
import Link from 'next/link'

const Map = dynamic(() => import('@/components/map'), { ssr: false })

export default function Home() {
  const [modalOpen, setModalOpen] = useState(false)
  const [properties, setProperties] = useState<Properties | undefined>(
    undefined
  )

  const HandleSelectNeighborhood = (properties: Properties) => {
    setProperties(properties)
    setModalOpen(true)
  }

  return (
    <>
      <Head>
        <title>Ubirata test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link
          href="https://www.ubirata.ai/"
          target="_Blank"
          className={styles.containerLogo}
        >
          <Image
            src={Logo_Ubirata_Positive}
            alt="Logo Ubiratã"
            width={1000}
            height={296}
            className={styles.ubirataLogo}
          />
          <p>| Test</p>
        </Link>

        <Map
          HandleSelectNeighborhood={HandleSelectNeighborhood}
          data-testid="map"
        />
        {modalOpen && (
          <Modal setModalOpen={setModalOpen}>
            <ChartPopulationInfo properties={properties} />
          </Modal>
        )}
      </main>
    </>
  )
}
