import Head from 'next/head'
import * as S from './index.style'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <S.Heading>welcome to next.js!</S.Heading>
      </main>
    </>
  )
}
